"""
Report Repository Interface
"""

from abc import ABC
from typing import List, Optional
from datetime import datetime
from src.report import Report

from repositories.repository_interface import Repository


class ReportRepository(Repository[Report, str], ABC):
    """
    Entity-specific repository for Report.
    """
    
    def find_by_generated_by(self, user_id: str) -> List[Report]:
        """Find all reports generated by a specific user"""
        pass
    
    def find_by_date_range(self, start: datetime, end: datetime) -> List[Report]:
        """Find reports generated within a date range"""
        pass