"""
In-Memory implementation of ReportRepository
"""

from typing import Dict, List, Optional
from datetime import datetime
from src.report import Report

from repositories.report_repository import ReportRepository


class InMemoryReportRepository(ReportRepository):
    """
    Stores Report objects in a Python dictionary (HashMap).
    """
    
    def __init__(self):
        self._storage: Dict[str, Report] = {}
    
    def save(self, entity: Report) -> None:
        """Save or update a report"""
        self._storage[entity.get_report_id()] = entity
    
    def find_by_id(self, id: str) -> Optional[Report]:
        """Find a report by ID"""
        return self._storage.get(id)
    
    def find_all(self) -> List[Report]:
        """Get all reports"""
        return list(self._storage.values())
    
    def delete(self, id: str) -> None:
        """Delete a report by ID"""
        if id in self._storage:
            del self._storage[id]
    
    def exists_by_id(self, id: str) -> bool:
        """Check if a report exists"""
        return id in self._storage
    
    def find_by_generated_by(self, user_id: str) -> List[Report]:
        """Find all reports generated by a specific user"""
        return [r for r in self._storage.values() if r._generated_by == user_id]
    
    def find_by_date_range(self, start: datetime, end: datetime) -> List[Report]:
        """Find reports generated within a date range"""
        return [r for r in self._storage.values() 
                if r._generated_at and start <= r._generated_at <= end]